---
- name: Setup F5
  hosts: Vlab
  connection: local

  gather_facts: False
  vars:

    username: username
    guest_password: guest_password
    state: present
    session_state: disabled
    monitor_state: disabled
    partition: common
  tasks:
    - name: Disable from F5
      bigip_node:
        validate_certs: False
        host: 10.80.5.100
        name: "{{ item }}"
        server: '{{ inventory_hostname }}'
        user: "{{ username }}"
        password: "{{ guest_password }}"
        state: "{{ state }}"
        session_state: "{{ session_state }}"
        monitor_state: "{{ monitor_state }}"
        partition: "{{ partition }}"
      with_items:
        - coops_Test
        
