---
- name: Setup F5
  hosts: localhost
  gather_facts: False
  vars:
    big_IP_host:
    username:
    guest_password:
    state: present
    session_state: disabled
    monitor_state: disabled
    partition: common
  tasks:
    - name: Disable from F5
      bigip_node:
        validate_cert: False
        name: 10.80.5.100
          server="{{ big_IP_host }}"
          user="{{ username }}"
          password="{{ guest_password }}"
          state="{{ state }}"
          session_state="{{ session_state }}"
          monitor_state="{{ monitor_state }}"
          partition="{{ partition }}"
