---
- hosts: test
- name: Disable from F5
  bigip_node:
    server: {{ big_IP_host }}
    user: {{ username }}
    password: {{ guest_password }}
    state: present
    session_state: disabled
    monitor_state: disabled
    partition: common
