- name: Terminate instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ec2_access_key:
    ec2_secret_key:
    ec2_region: us-east-1
    ec2_id:
  tasks:
    - name: Terminate instances that were previously launched
      ec2: >
        instance_ids: '{{ ec2_id }}'
        region="{{ ec2_region }}"
        state: 'absent'
