- name: Terminate instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ec2_access_key:
    ec2_secret_key:
    ec2_region: us-east-1
  tasks:
    - name: Terminate instances that were previously launched
      ec2: >
        instance_ids:
          - i-04ea4eb78413ae1b4
        region="{{ ec2_region }}"
        state: 'absent'
