- name: Terminate instances
  hosts: localhost
  connection: local
  vars:
    ec2_access_key:
    ec2_secret_key:
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'
