- name: Terminate instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ec2_access_key:
    ec2_secret_key:
    ec2_instance_ids:
    ec2_region: us-east-1
  tasks:
    - name: Terminate instances that were previously launched
      ec2: >
        state: 'absent'
        region="{{ ec2_region }}"
        instance_ids: '{{ ec2_instance_ids }}'
