---
- name: Create a test instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ec2_access_key:
    ec2_secret_key:
    ec2_region: us-east-1
    ec2_image: ami-0b33d91d
    ec2_instance_type: t2.micro
    ec2_keypair:
    ec2_security_group: default
    ec2_instance_count: 1
    ec2_tag: test_install
  tasks:
    - name: LaunchInstance
      ec2: >
        access_key="{{ ec2_access_key }}"
        secret_key="{{ ec2_secret_key }}"
        keypair="{{ ec2_keypair }}"
        group="{{ ec2_security_group }}"
        type="{{ ec2_image }}"
        region="{{ ec2_region }}"
        image="{{ ec2_image }}"
        count="{{ ec2_instance_count }}"
      register: ec2
