---
- name: Identify hosts
  hosts: all
  user: cloud-user
  become: yes
  gather_facts: true

  tasks:
    - name: Install Security Updates
      command: /usr/bin/yum update -y {{item}}
      with_items:
        - security
