---
- name: Identify hosts
  hosts: rheltest
  user: cloud-user
  sudo: yes
  gather_facts: true

  tasks:
    - name: Install Security Updates
      yum:
        name: yum-plugin-security
        state: latest
